export const qualityTagOptions = [
  { label: '100% Natural', value: '100% Natural' },
  { label: '1% for the Planet', value: '1% for the Planet' },
  { label: 'B Corp', value: 'B Corp' },
  { label: 'Biodynamic', value: 'Biodynamic' },
  { label: 'CBD', value: 'CBD' },
  { label: 'Compostable Packaging', value: 'Compostable Packaging' },
  { label: 'Cultivated Foods', value: 'Cultivated Foods' },
  { label: 'Dairy-Free', value: 'Dairy-Free' },
  { label: 'Direct Fair Trade', value: 'Direct Fair Trade' },
  { label: 'Fair Trade', value: 'Fair Trade' },
  { label: 'Fully Traceable Ingredients', value: 'Fully Traceable Ingredients' },
  { label: 'Gluten-Free', value: 'Gluten-Free' },
  { label: 'Glyphosate Residue Free', value: 'Glyphosate Residue Free' },
  { label: 'Keto', value: 'Keto' },
  { label: 'Kosher', value: 'Kosher' },
  { label: 'No Artificial Sweeteners', value: 'No Artificial Sweeteners' },
  { label: 'Non-GMO', value: 'Non-GMO' },
  { label: 'Non-GMO Project Verified', value: 'Non-GMO Project Verified' },
  { label: 'Nut-Free', value: 'Nut-Free' },
  { label: 'Organic', value: 'Organic' },
  { label: 'Paleo', value: 'Paleo' },
  { label: 'Plant-Based', value: 'Plant-Based' },
  { label: 'Probiotic', value: 'Probiotic' },
  { label: 'Raw', value: 'Raw' },
  { label: 'Recyclable Packaging', value: 'Recyclable Packaging' },
  { label: 'Regenerative Agriculture', value: 'Regenerative Agriculture' },
  { label: 'Soy-Free', value: 'Soy-Free' },
  { label: 'Sugar-Free', value: 'Sugar-Free' },
  { label: 'Sustainably Grown', value: 'Sustainably Grown' },
  { label: 'THC', value: 'THC' },
  { label: 'Upcycled', value: 'Upcycled' },
  { label: 'USDA Organic', value: 'USDA Organic' },
  { label: 'Vegan', value: 'Vegan' },
];